# Permalinks
permalink:      /:title

# Setup
title:          The Penn Treaty Elm
paginate:       40
baseurl:        "/penn-treaty-elm"
url:            "http://ds.haverford.edu/penn-treaty-elm"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Haverford College Libraries
  url:          http://library.haverford.edu

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/mzarafon/penn-treaty-elm

# Gems
plugins:
  - jekyll-paginate
